### PR TITLE
`plugins = numpy.typing.mypy_plugin` to `setup.cfg`

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Review by richrines1 — APPROVED** [review]
lgtm

**Comment by richrines1** [comment]
actually shouldn't `disallow_incomplete_defs = True` be in setup.cfg as well?

**Comment by vtomole** [comment]
@richrines1  It's there:

https://github.com/SupertechLabs/general-superstaq/blob/22b0a707094904b2ca23b85858b417735d5510db/general_superstaq/check/setup.cfg#L31

**Comment by richrines1** [comment]
> @richrines1 It's there:
> 
> https://github.com/SupertechLabs/general-superstaq/blob/22b0a707094904b2ca23b85858b417735d5510db/general_superstaq/check/setup.cfg#L31

oops copy-pasted the wrong line. i meant `disallow_any_generics`

**Comment by vtomole** [comment]
@richrines1 We can't do that yet because i haven't fixed all the generics in SS yet.

**Comment by vtomole** [comment]
Discussed IRL. SS won't throw an error if we add this.

**Pull request merged**
